config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :items

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  

  get 'thankyou' => 'landings#thankyou'
  get 'unsuccessful' => 'landings#unsuccessful'

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  get 'users/:id' => 'users#show'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:is_email_visible, 
      :is_phone_number_visible, :public_identifier, :legal_name,
      :gender, :is_gender_visible, :phone_number, :description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:is_email_visible, 
    :is_phone_number_visible, :public_identifier, :legal_name,
    :gender, :is_gender_visible, :phone_number, :description])    
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :photo, :price, :first_advertised_date, :is_advertisied, :user_id)
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    @items = Item.all
  end

# This is called when a transaction is concluded successfully!

  def thankyou
  end

# This is called when a transaction doesn't go well..

  def unsuccessful
  end



end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Toys on Tracks", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :photo, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :photo, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :price, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :first_advertised_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :first_advertised_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_advertisied, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :is_advertisied, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  items_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Item %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => Item %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:first_advertised_date) %></th>
      <th><%= model_class.human_attribute_name(:is_advertisied) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.photo %></td>
        <td><%= item.price %></td>
        <td><%= item.first_advertised_date %></td>
        <td><%= item.is_advertisied %></td>
        <td><%=l item.created_at, format: :long %></td>
        <td>
          <%= link_to item_path(item), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to item_path(item), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Item %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => Item %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @item.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @item.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:photo) %></dt>
      <dd><pre class="prettyprint"><%= @item.photo %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @item.price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_advertised_date) %></dt>
      <dd><pre class="prettyprint"><%= @item.first_advertised_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:is_advertisied) %></dt>
      <dd><pre class="prettyprint"><%= @item.is_advertisied %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/landings/index.html.erb
<h1>Welcome to Toys on Tracks</h1>
<p>What item would you like to buy?</p>

<%- model_class = Item -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:first_advertised_date) %></th>
      <th><%= model_class.human_attribute_name(:is_advertisied) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.photo %></td>
        <td><%= item.price %></td>
        <td><%= item.first_advertised_date %></td>
        <td><%= item.is_advertisied %></td>
        <td><%=l item.created_at, format: :long %></td>
        <td>
          <%= link_to item_path(item), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to item_path(item), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/landings/thankyou.html.erb
<% content_for :title do %>Toys on Tracks Thanks You!<% end %>

<h1>Thank You</h1>
<p>Your transaction works! You have just bought something. Would you like to buy <a href="/">something more</a>?</p>

app/views/landings/unsuccessful.html.erb
<% content_for :title do %>Toys on Tracks Doesn't Thank You!<% end %>

<h1>No Thank You!</h1>
<p>Your transaction was completely unsuccessful! Why it <em>was</em> unsuccessful...
well, this website isn't going to be the judge. But perhaps you want to give buying <a href="/">another shot</a>? </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <link rel="shortcut icon" href="/train.ico">
  <title><%= content_for?(:title) ? yield(:title) : "Toys on Tracks" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<div class="container">
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>
<div class="navbar navbar-default navbar-fixed-bottom">
<div class="container">
<p>
   Copyright © Peter Murphy 2018. Powered by <a href="http://rubyonrails.org/">Ruby on Rails</a>. 
   Uses imagery from <a href="https://thenounproject.com/walkingfearless/uploads/">João Miranda</a>
   courtesy of <a href="https://thenounproject.com/">The Noun Project</a>. 
</p>
</div>
</div>
</div>
</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.public_identifier %></h1>

<p><%= @user.description %></p>

<% if @user.is_email_visible %>
<p><strong>Email</strong>: <%= @user.email %></p>
<% else %>

<% end %>

<% if @user.is_phone_number_visible %>
<p><strong>Phone Number</strong>: <%= @user.phone_number %></p>
<% else %>

<% end %>

<% if @user.is_gender_visible %>
<p><strong>Gender</strong>: <%= @user.gender %></p>
<% else %>

<% end %>